services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    labels:
      - "gh.codespaces.port-name=Grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource,agenty-flowcharting-panel,yesoreyeram-boomtable-panel,grafana-simple-json-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=agenty-flowcharting-panel
    restart: unless-stopped
    volumes:
       - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    labels:
      - "gh.codespaces.port-name=Prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped


  mosquitto:
    image: eclipse-mosquitto
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto:/mosquitto

  mqtt-exporter:
    image: kpetrem/mqtt-exporter:latest
    depends_on:
      - mosquitto
    ports: ["9000:9000"]
    environment:
      - MQTT_ADDRESS=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=planta/+/+
      # - MQTT_USERNAME=mqtt_user
      # - MQTT_PASSWORD=mqtt_pass
      - PROMETHEUS_PORT=9000
      - PROMETHEUS_PREFIX=mqtt_


    # volumes:
    #   - ./mqtt-exporter:/config



# PRODUCERS

  mqtt-sensor1-producer:
    build:
      context: ./metrics-generator
    container_name: mqtt-sensor1-producer
    restart: unless-stopped
    command: 
      - node
      - mqtt-producers/sensor1.js
    depends_on:
      - mosquitto



  mqtt-sensor2-producer:
    build:
      context: ./metrics-generator
    container_name: mqtt-sensor2-producer
    restart: unless-stopped
    command: 
      - node
      - mqtt-producers/sensor2.js
    depends_on:
      - mosquitto      